[tool.poetry]
name = "mylib"
version = "0.0.0"
description = "A library"
authors = ["Example <hello@example.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "~=7.1"

[build-system]
requires = ["poetry>=1.1.13"]
build-backend = "poetry.masonry.api"
